'''
Created on 09.01.2010

@author: danfocus
'''

# FLAP
FLAP_STARTMARKER = 0x2A
FLAP_HRD_SIZE = 6
FLAP_VERSION = 1

#  FLAP frame types
FLAP_FRAME_SIGNON = 1
FLAP_FRAME_DATA = 2
FLAP_FRAME_ERROR = 3
FLAP_FRAME_SIGNOFF = 4
FLAP_FRAME_KEEP_ALIVE = 5

# FLAP signon tags
FL_SIGNON_NAME = 3
FL_SIGNON_COOKIE = 6
FL_SIGNON_COUNTRY = 14
FL_SIGNON_LANGUAGE = 15
FL_SIGNON_DISTR_NUM = 20
FL_SIGNON_ID_NUM = 22
FL_SIGNON_MAJOR_VERSION = 23
FL_SIGNON_MINOR_VERSION = 24
FL_SIGNON_POINT_VERSION = 25
FL_SIGNON_BUILD_NUM = 26
FL_SIGNON_RECONNECT= 148

# SNAC types
SN_TYP_REGISTRATION = 23

# SNAC 23 subtypes
SN_IES_AUTHxLOGIN = 2
SN_IES_LOGINxREPLY = 3
SN_IES_AUTHxREQUEST = 6
SN_IES_AUTHxKEY = 7





AIM_MD5_STRING = "AOL Instant Messenger (SM)"